accent_color: '#2d72d9'
lang: en-US
title: Maximilien Roberti
description: >-
  This is the personal website of Maximilien Roberti. He is a software engineer
  specilized in Artificial Inteligence.
baseurl: ''
url: 'https://important-oak-4747e.netlify.com/'
permalink: '/:title'
favicon: /images/logomr-v3.png
disqus: justgoodthemes
navigation:
  - text: Home
    url: /
  - text: About
    url: /about/
  - text: Style Guide
    url: /style-guide/
  - text: Tags
    url: /tags/
  - text: Download
    url: 'https://github.com/JustGoodThemes/Scriptor-Jekyll-Theme'
footer:
  content: >-
    &copy; Scriptor all rights reserved. Theme by
    [JustGoodThemes](https://www.justgoodthemes.com).
  has_social: true
plugins:
  - jekyll-paginate
paginate: 3
paginate_path: '/page:num/'
markdown: kramdown
sass:
  sass_dir: _sass
  style: compressed
