accent_color: '#2d72d9'
lang: en-US
title: Maximilien Roberti
description: >-
  Machine Learning Engineer passionate about cutting-edge technology and solving
  real-world problems.
baseurl: ''
url: 'https://maximilienroberti.github.io'
permalink: '/:title'
favicon: /images/logomr-v5.png
disqus: maximilienroberti
navigation:
  - text: Home
    url: /
  - text: Tags
    url: /tags
  - text: About
    url: /about
  - text: Resume
    url: >-
      https://drive.google.com/file/d/1oxDqU2Jjwwn0o0Hw6kn-A0EQG_KBN5t_/view?usp=sharing
footer:
  content: '&copy; All rights reserved.'
  has_social: true
plugins:
  - jekyll-paginate
paginate: 3
paginate_path: '/page:num/'
markdown: kramdown
sass:
  sass_dir: _sass
  style: compressed
