accent_color: '#2d72d9'
lang: en-US
title: Maximilien Roberti
description: >-
  This is the personal website of Maximilien Roberti. He is a software engineer
  specilized in Artificial Inteligence.
baseurl: ''
url: 'https://maximilienroberti.github.io'
permalink: '/:title'
favicon: /images/logomr-v6.svg
disqus: maximilienroberti
navigation:
  - text: Home
    url: /
  - text: Tags
    url: /tags
  - text: About
    url: /about
  - text: Resume
    url: >-
      https://drive.google.com/file/d/1pvlV0biYjQCMDy0dHgypI82lAeNsEs93/view?usp=sharing
footer:
  content: '&copy; All rights reserved.'
  has_social: true
plugins:
  - jekyll-paginate
paginate: 3
paginate_path: '/page:num/'
markdown: kramdown
sass:
  sass_dir: _sass
  style: compressed
